version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd document-translation-main/util/getOptions
      - npm ci
  pre_build:
    commands:
      - echo "Generating config file..."
      - npm run start
      - ls -la
      - echo "Generated config.json:"
      - cat config.json
      - mkdir -p ../../config
      - cp config.json ../../config/
      - cd ../../
      - echo "Config directory contents:"
      - ls -la config/
  build:
    commands:
      - echo "Setting up infrastructure..."
      - cd infrastructure
      - cp ../config/config.json .
      - echo "Infrastructure config.json:"
      - cat config.json
      - npm ci
      - npm run cdk synth
artifacts:
  files:
    - document-translation-main/infrastructure/cdk.out/**/*
  base-directory: .
  discard-paths: false 